import type { AgentId } from "./mock-data";

export type SkillTemplate = {
  agent: AgentId;
  name: string;
  summary: string;
  code: string;
  outputSummary: string;
  durationMs: number;
};

const CASH_FORECAST = `"""
treasury/cash_forecast.py — 30-day cash projection
Generated by Codex Prime for Treasury Sentinel.
"""
import pandas as pd

SAFETY_FLOOR = 5_000
OPENING_BALANCE = 32_400

inflows = [
    {"day": 5,  "amount":  4_200, "label": "Hexa Studios (INV-1025)"},
    {"day": 18, "amount":  4_400, "label": "Mango Retail (INV-1011)"},
    {"day": 28, "amount":  8_600, "label": "Recurring MRR (Stripe)"},
]
outflows = [
    {"day": 12, "amount": 6_200,  "label": "Vendor: Acme Cloud Hosting"},
    {"day": 14, "amount": 1_800,  "label": "Vendor: Twilio"},
    {"day": 15, "amount": 22_000, "label": "Payroll"},
    {"day": 22, "amount": 3_170,  "label": "AWS Reserved"},
]

def project(days: int = 30) -> pd.DataFrame:
    bal = OPENING_BALANCE
    rows = []
    for d in range(days + 1):
        delta = sum(i["amount"] for i in inflows if i["day"] == d) \\
              - sum(o["amount"] for o in outflows if o["day"] == d)
        bal += delta
        rows.append({"day": d, "balance": bal, "below_floor": bal < SAFETY_FLOOR})
    return pd.DataFrame(rows)

if __name__ == "__main__":
    df = project()
    breach = df[df["below_floor"]].head(1)
    if not breach.empty:
        d = int(breach.iloc[0]["day"])
        b = int(breach.iloc[0]["balance"])
        print(f"CRUNCH on Day {d}: balance {b:,} USD")
    print(df.tail(10).to_string(index=False))
`;

const SEGMENT_CUSTOMERS = `"""
collection/segment_customers.py — payment-behavior classifier
"""
import pandas as pd

def classify(invoices: pd.DataFrame, history: pd.DataFrame) -> pd.DataFrame:
    rates = history.groupby("customer")["paid_late"].mean()
    invoices["chronic"] = invoices["customer"].map(rates) > 0.4
    invoices["tone"] = invoices.apply(
        lambda r: "firm" if r["chronic"] or r["days_late"] >= 14 else "friendly",
        axis=1,
    )
    invoices["priority"] = invoices["amount"] / (invoices["days_late"].clip(lower=1))
    return invoices.sort_values("priority", ascending=False)
`;

const DRAFT_EMAIL = `"""
collection/draft_email.py — tone-aware reminder drafts
"""
TEMPLATES = {
    "friendly": (
        "Hi {first_name},\\n\\nHope all's well at {company}. Just a quick nudge — "
        "Invoice {invoice_id} for {amount} (issued {issued}) is now {days_late} "
        "days past the {terms} term. Could you check with your AP team when "
        "we can expect payment?\\n\\nHappy to jump on a call if helpful.\\n\\nBest,\\nAlex"
    ),
    "firm": (
        "Hi {first_name},\\n\\nInvoice {invoice_id} ({amount}) is now {days_late} "
        "days overdue. Please remit by end of week, or reach out today to "
        "arrange a payment plan.\\n\\nThanks,\\nAlex"
    ),
}

def draft(invoice: dict, tone: str = "friendly") -> str:
    return TEMPLATES[tone].format(**invoice)
`;

const RENEWAL_SCAN = `"""
subscription/renewal_scan.py — renewal radar
"""
ALERT_WINDOWS = [45, 30, 14, 7, 2]

def scan(subscriptions, cash_buffer):
    alerts = []
    for s in subscriptions:
        if s["cancel_window_closes_in"] <= 7 and not s["essential"]:
            alerts.append({
                "level": "URGENT",
                "vendor": s["vendor"],
                "savings_if_cancelled": s["annual_cost"],
                "deadline_days": s["cancel_window_closes_in"],
            })
        elif cash_buffer < 10_000 and not s["essential"] and s["monthly_cost"] <= 300:
            alerts.append({
                "level": "PAUSE",
                "vendor": s["vendor"],
                "monthly_savings": s["monthly_cost"],
            })
    return sorted(alerts, key=lambda a: 0 if a["level"] == "URGENT" else 1)
`;

const TX_SAAS_CALC = `"""
tax/tx_saas_calc.py — Texas SaaS sales-tax calculator

Legal basis:
- TX Tax Code 151.0101: SaaS is taxable as a data-processing service.
- 20% of SaaS revenue is EXEMPT (TX Tax Code 151.351).
- Economic nexus: $500K total revenue or 200 transactions,
  but CloudMetrics has physical nexus via remote employee -> $0 threshold.
- State rate: 6.25%. Average local rate: 1.94%.
"""
TX_STATE_RATE = 0.0625
TX_AVG_LOCAL_RATE = 0.0194
SAAS_EXEMPT_PCT = 0.20

def compute(revenue_ytd: float, threshold: float = 100_000) -> dict:
    nexus_crossed = revenue_ytd >= threshold
    taxable_base = revenue_ytd * (1 - SAAS_EXEMPT_PCT)
    rate = TX_STATE_RATE + TX_AVG_LOCAL_RATE
    tax_owed = round(taxable_base * rate, 2) if nexus_crossed else 0.0
    return {
        "nexus_crossed": nexus_crossed,
        "taxable_base": round(taxable_base, 2),
        "effective_rate": rate,
        "tax_owed": tax_owed,
        "citation": "TX Tax Code 151.0101 (SaaS) + 151.351 (20% exemption)",
    }

if __name__ == "__main__":
    print(compute(100_200))
`;

const OPTIMIZE_SURVIVAL = `"""
scenario/optimize_survival.py — cash-crunch survival planner

Uses PuLP for mixed-integer optimization. Decision variables:
  - which overdue invoices to prioritize for collection
  - which vendor payments to delay
  - which non-essential subscriptions to pause
Objective: maximize Day-18 buffer subject to keeping balance > floor.
"""
from pulp import LpProblem, LpMaximize, LpVariable, lpSum, LpBinary

def solve(invoices, vendors, subs, daily_balance, day_target=18):
    prob = LpProblem("survival", LpMaximize)
    x = {i["id"]: LpVariable(f"collect_{i['id']}", cat=LpBinary) for i in invoices}
    y = {v["id"]: LpVariable(f"delay_{v['id']}",   cat=LpBinary) for v in vendors}
    z = {s["id"]: LpVariable(f"pause_{s['id']}",   cat=LpBinary) for s in subs if not s["essential"]}

    inflow  = lpSum(x[i["id"]] * i["amount"] * 0.85       for i in invoices)
    delayed = lpSum(y[v["id"]] * v["amount"]              for v in vendors)
    paused  = lpSum(z[s["id"]] * s["monthly_cost"]        for s in subs if not s["essential"])

    prob += inflow + delayed + paused
    prob += daily_balance[day_target] + inflow + delayed + paused >= 5_000

    prob.solve()
    return {
        "collect":     [i["id"] for i in invoices if x[i["id"]].value() == 1],
        "delay":       [v["id"] for v in vendors  if y[v["id"]].value() == 1],
        "pause":       [s["id"] for s in subs     if not s["essential"] and z[s["id"]].value() == 1],
        "buffer_gain": int(prob.objective.value()),
    }
`;

export const SKILL_TEMPLATES: Record<string, SkillTemplate> = {
  cash_forecast: {
    agent: "treasury",
    name: "cash_forecast",
    summary: "30-day forward cash projection with sensitivity on payment timing.",
    outputSummary: "Projected Day-18 balance: -$3,200 (below safety floor of $5,000)",
    durationMs: 1840,
    code: CASH_FORECAST,
  },
  segment_customers: {
    agent: "collection",
    name: "segment_customers",
    summary: "Classify customers as chronic-late vs. one-time delay using payment history.",
    outputSummary: "6 overdue invoices · 2 chronic-late · prioritized by recoverable cash impact",
    durationMs: 1260,
    code: SEGMENT_CUSTOMERS,
  },
  draft_email: {
    agent: "collection",
    name: "draft_email",
    summary: "Generate tone-aware reminder email body per invoice + customer relationship.",
    outputSummary: "3 drafts queued (auto-action), 1 escalated for approval (> $1k)",
    durationMs: 980,
    code: DRAFT_EMAIL,
  },
  renewal_scan: {
    agent: "subscription",
    name: "renewal_scan",
    summary: "Daily scan: renewals, cancel windows, price escalations, early-pay discounts.",
    outputSummary: "1 URGENT (Slack), 1 WATCH (AWS), 1 OPTIMIZE (vendor early-pay)",
    durationMs: 720,
    code: RENEWAL_SCAN,
  },
  tx_saas_calc: {
    agent: "tax",
    name: "tx_saas_calc",
    summary: "Texas economic nexus check + SaaS tax calc per TX Tax Code 151.0101.",
    outputSummary: "TX nexus CROSSED at $100,200 YTD. Tax owed: $1,420.50",
    durationMs: 2110,
    code: TX_SAAS_CALC,
  },
  optimize_survival: {
    agent: "scenario",
    name: "optimize_survival",
    summary: "Mixed-integer optimization to rank 3 survival plans for a cash crunch.",
    outputSummary: "3 scenarios generated. A (92% success), B (85%), C (78%).",
    durationMs: 3340,
    code: OPTIMIZE_SURVIVAL,
  },
};

export type SkillKey = keyof typeof SKILL_TEMPLATES;
