/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSnapshotRouteImport } from './routes/api/snapshot'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiTreasuryProjectionRouteImport } from './routes/api/treasury.projection'
import { Route as ApiLlmHealthRouteImport } from './routes/api/llm.health'
import { Route as ApiCsvIngestRouteImport } from './routes/api/csv.ingest'
import { Route as ApiConnectorsSyncRouteImport } from './routes/api/connectors.sync'
import { Route as ApiConnectorsListRouteImport } from './routes/api/connectors.list'
import { Route as ApiCodexStreamRouteImport } from './routes/api/codex.stream'
import { Route as ApiAgentsRunRouteImport } from './routes/api/agents.run'
import { Route as ApiAgentsCustomizeRouteImport } from './routes/api/agents.customize'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotRoute = ApiSnapshotRouteImport.update({
  id: '/api/snapshot',
  path: '/api/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTreasuryProjectionRoute = ApiTreasuryProjectionRouteImport.update({
  id: '/api/treasury/projection',
  path: '/api/treasury/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmHealthRoute = ApiLlmHealthRouteImport.update({
  id: '/api/llm/health',
  path: '/api/llm/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCsvIngestRoute = ApiCsvIngestRouteImport.update({
  id: '/api/csv/ingest',
  path: '/api/csv/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsSyncRoute = ApiConnectorsSyncRouteImport.update({
  id: '/api/connectors/sync',
  path: '/api/connectors/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsListRoute = ApiConnectorsListRouteImport.update({
  id: '/api/connectors/list',
  path: '/api/connectors/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexStreamRoute = ApiCodexStreamRouteImport.update({
  id: '/api/codex/stream',
  path: '/api/codex/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRunRoute = ApiAgentsRunRouteImport.update({
  id: '/api/agents/run',
  path: '/api/agents/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsCustomizeRoute = ApiAgentsCustomizeRouteImport.update({
  id: '/api/agents/customize',
  path: '/api/agents/customize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/architecture': typeof ArchitectureRoute
  '/policy': typeof PolicyRoute
  '/skills': typeof SkillsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/agents/customize': typeof ApiAgentsCustomizeRoute
  '/api/agents/run': typeof ApiAgentsRunRoute
  '/api/codex/stream': typeof ApiCodexStreamRoute
  '/api/connectors/list': typeof ApiConnectorsListRoute
  '/api/connectors/sync': typeof ApiConnectorsSyncRoute
  '/api/csv/ingest': typeof ApiCsvIngestRoute
  '/api/llm/health': typeof ApiLlmHealthRoute
  '/api/treasury/projection': typeof ApiTreasuryProjectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/architecture': typeof ArchitectureRoute
  '/policy': typeof PolicyRoute
  '/skills': typeof SkillsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/agents/customize': typeof ApiAgentsCustomizeRoute
  '/api/agents/run': typeof ApiAgentsRunRoute
  '/api/codex/stream': typeof ApiCodexStreamRoute
  '/api/connectors/list': typeof ApiConnectorsListRoute
  '/api/connectors/sync': typeof ApiConnectorsSyncRoute
  '/api/csv/ingest': typeof ApiCsvIngestRoute
  '/api/llm/health': typeof ApiLlmHealthRoute
  '/api/treasury/projection': typeof ApiTreasuryProjectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/architecture': typeof ArchitectureRoute
  '/policy': typeof PolicyRoute
  '/skills': typeof SkillsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/agents/customize': typeof ApiAgentsCustomizeRoute
  '/api/agents/run': typeof ApiAgentsRunRoute
  '/api/codex/stream': typeof ApiCodexStreamRoute
  '/api/connectors/list': typeof ApiConnectorsListRoute
  '/api/connectors/sync': typeof ApiConnectorsSyncRoute
  '/api/csv/ingest': typeof ApiCsvIngestRoute
  '/api/llm/health': typeof ApiLlmHealthRoute
  '/api/treasury/projection': typeof ApiTreasuryProjectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/architecture'
    | '/policy'
    | '/skills'
    | '/api/ask'
    | '/api/snapshot'
    | '/api/agents/customize'
    | '/api/agents/run'
    | '/api/codex/stream'
    | '/api/connectors/list'
    | '/api/connectors/sync'
    | '/api/csv/ingest'
    | '/api/llm/health'
    | '/api/treasury/projection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/architecture'
    | '/policy'
    | '/skills'
    | '/api/ask'
    | '/api/snapshot'
    | '/api/agents/customize'
    | '/api/agents/run'
    | '/api/codex/stream'
    | '/api/connectors/list'
    | '/api/connectors/sync'
    | '/api/csv/ingest'
    | '/api/llm/health'
    | '/api/treasury/projection'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/architecture'
    | '/policy'
    | '/skills'
    | '/api/ask'
    | '/api/snapshot'
    | '/api/agents/customize'
    | '/api/agents/run'
    | '/api/codex/stream'
    | '/api/connectors/list'
    | '/api/connectors/sync'
    | '/api/csv/ingest'
    | '/api/llm/health'
    | '/api/treasury/projection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ArchitectureRoute: typeof ArchitectureRoute
  PolicyRoute: typeof PolicyRoute
  SkillsRoute: typeof SkillsRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiSnapshotRoute: typeof ApiSnapshotRoute
  ApiAgentsCustomizeRoute: typeof ApiAgentsCustomizeRoute
  ApiAgentsRunRoute: typeof ApiAgentsRunRoute
  ApiCodexStreamRoute: typeof ApiCodexStreamRoute
  ApiConnectorsListRoute: typeof ApiConnectorsListRoute
  ApiConnectorsSyncRoute: typeof ApiConnectorsSyncRoute
  ApiCsvIngestRoute: typeof ApiCsvIngestRoute
  ApiLlmHealthRoute: typeof ApiLlmHealthRoute
  ApiTreasuryProjectionRoute: typeof ApiTreasuryProjectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshot': {
      id: '/api/snapshot'
      path: '/api/snapshot'
      fullPath: '/api/snapshot'
      preLoaderRoute: typeof ApiSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/treasury/projection': {
      id: '/api/treasury/projection'
      path: '/api/treasury/projection'
      fullPath: '/api/treasury/projection'
      preLoaderRoute: typeof ApiTreasuryProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm/health': {
      id: '/api/llm/health'
      path: '/api/llm/health'
      fullPath: '/api/llm/health'
      preLoaderRoute: typeof ApiLlmHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csv/ingest': {
      id: '/api/csv/ingest'
      path: '/api/csv/ingest'
      fullPath: '/api/csv/ingest'
      preLoaderRoute: typeof ApiCsvIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/sync': {
      id: '/api/connectors/sync'
      path: '/api/connectors/sync'
      fullPath: '/api/connectors/sync'
      preLoaderRoute: typeof ApiConnectorsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/list': {
      id: '/api/connectors/list'
      path: '/api/connectors/list'
      fullPath: '/api/connectors/list'
      preLoaderRoute: typeof ApiConnectorsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/stream': {
      id: '/api/codex/stream'
      path: '/api/codex/stream'
      fullPath: '/api/codex/stream'
      preLoaderRoute: typeof ApiCodexStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/run': {
      id: '/api/agents/run'
      path: '/api/agents/run'
      fullPath: '/api/agents/run'
      preLoaderRoute: typeof ApiAgentsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/customize': {
      id: '/api/agents/customize'
      path: '/api/agents/customize'
      fullPath: '/api/agents/customize'
      preLoaderRoute: typeof ApiAgentsCustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ArchitectureRoute: ArchitectureRoute,
  PolicyRoute: PolicyRoute,
  SkillsRoute: SkillsRoute,
  ApiAskRoute: ApiAskRoute,
  ApiSnapshotRoute: ApiSnapshotRoute,
  ApiAgentsCustomizeRoute: ApiAgentsCustomizeRoute,
  ApiAgentsRunRoute: ApiAgentsRunRoute,
  ApiCodexStreamRoute: ApiCodexStreamRoute,
  ApiConnectorsListRoute: ApiConnectorsListRoute,
  ApiConnectorsSyncRoute: ApiConnectorsSyncRoute,
  ApiCsvIngestRoute: ApiCsvIngestRoute,
  ApiLlmHealthRoute: ApiLlmHealthRoute,
  ApiTreasuryProjectionRoute: ApiTreasuryProjectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
